# S3 bucket path
s3_crawled_csv: 
s3_crawled_csv_region: 
s3_crewled_parquet: 
s3_crawled_parquet_region:

# RDS settings
postgresql_database: newsdesk
postgresql_host: newsdeskdb.ct0guinjlxs2.ap-northeast-2.rds.amazonaws.com
postgresql_port: 5432
postgresql_user: newsdesk
postgresql_password: ybigtaengineering
