# S3 bucket path
s3_crawled_csv: 
s3_crawled_csv_region: 
s3_crewled_parquet: 
s3_crawled_parquet_region:

# RDS settings
postgresql_database: newsdesk
postgresql_host: newsdeskdb.ct0guinjlxs2.ap-northeast-2.rds.amazonaws.com
postgresql_port: 5432
postgresql_user: newsdesk
postgresql_password: ybigtaengineering

# naver news category
naver_news:
  urls:
    article_url: "http://news.naver.com/main/list.nhn?mode=LSD&mid=sec&sid1="
  category:
      정치: 100
      경제: 101
      사회: 102
      생활문화: 103
      세계: 104
      IT과학: 105
      오피니언: 110